name: Test Actions

on:
  schedule:
    - cron: "30-59/5 14 * * 1-5"
    - cron: "*/5 15-21 * * 1-5"
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - run: echo "GitHub Actions funcionando correctamente"